import 'package:flutter/material.dart';

import 'app_preferences.dart';

typedef TranslationParams = Map<String, Object>;

class AppLocalizations {
  AppLocalizations._();

  static const Map<String, Map<String, String>> _translations = {
    'es': {
      'common.light_mode': 'Modo claro',
      'common.dark_mode': 'Modo oscuro',

      'login.brand_description':
          'Gestiona estacionamientos en universidades,\ncentros comerciales y más',
      'login.welcome': 'Bienvenido',
      'login.subtitle': 'Inicia sesión para continuar',
      'login.email': 'Correo electrónico',
      'login.password': 'Contraseña',
      'login.sign_in': 'Iniciar sesión',
      'login.register': '¿No tienes cuenta? Regístrate aquí',
      'login.company_prompt':
          'Eres empresa? Te invitamos a nuestra pagina exclusiva para empresas.',
      'login.company_action': 'Ir al portal empresarial',
      'login.company_error': 'No se pudo abrir el portal empresarial',
      'login.empty_credentials': 'Ingrese correo y contraseña',
      'login.invalid_credentials': 'Correo o contraseña incorrectos',

      'register.create_account': 'Crear cuenta',
      'register.step_one': 'Paso 1 de 2 — Verificación de correo',
      'register.info':
          'Introduce tu correo electrónico para validar tu cuenta. Te enviaremos un código de verificación de 6 dígitos.',
      'register.email': 'Correo electrónico',
      'register.private_info': 'Tu información está protegida y es privada',
      'register.send_code': 'Enviar código de verificación',
      'register.enter_email': 'Por favor ingresa un correo',
      'register.error': 'Error al registrar usuario. Intenta nuevamente.',
      'register.already_account': '¿Ya tienes una cuenta? Inicia sesión',
      'register.next_steps': '¿Qué sucede a continuación?',
      'register.receive_code': 'Recibe el código',
      'register.receive_code_subtitle': 'En menos de 2 minutos en tu bandeja',
      'register.enter_digits': 'Ingresa los 6 dígitos',
      'register.enter_digits_subtitle': 'Válido por 10 minutos tras el envío',
      'register.complete_profile': 'Completa tu perfil',
      'register.complete_profile_subtitle':
          'Configura tu cuenta y empieza a usar la app',

      'validation.title': 'Verificar cuenta',
      'validation.step_two': 'Paso 2 de 2 — Ingresa tu código',
      'validation.sent_to': 'Código enviado a',
      'validation.code': 'Código de verificación',
      'validation.code_help': 'Ingresa los 6 dígitos recibidos en tu correo',
      'validation.expiry': 'El código expira en 10 minutos',
      'validation.not_received': '¿No recibiste el código? ',
      'validation.resend': 'Reenviar',
      'validation.validate_user': 'Validar usuario',
      'validation.complete_digits': 'Ingresa los 6 dígitos completos',
      'validation.invalid_code': 'Código inválido o expirado',

      'form.final_step': 'Paso final',
      'form.title': 'Completa tu registro',
      'form.subtitle': 'Rellena todos los campos para crear tu cuenta',
      'form.personal_data': 'Datos personales',
      'form.names': 'Nombres',
      'form.surnames': 'Apellidos',
      'form.enter_names': 'Ingrese sus nombres',
      'form.enter_surnames': 'Ingrese sus apellidos',
      'form.valid_dni': 'Ingrese un DNI válido',
      'form.phone': 'Teléfono',
      'form.valid_phone': 'Ingrese un teléfono válido',
      'form.birth_date': 'Fecha de nacimiento',
      'form.select_date': 'Seleccione su fecha',
      'form.vehicle_data': 'Datos del vehículo',
      'form.plate': 'Placa del auto',
      'form.model': 'Modelo del auto',
      'form.enter_model': 'Ingrese el modelo',
      'form.credentials': 'Credenciales',
      'form.password': 'Contraseña',
      'form.repeat_password': 'Repetir contraseña',
      'form.min_chars': 'Mínimo 8 caracteres',
      'form.passwords_mismatch': 'Las contraseñas no coinciden',
      'form.register': 'Registrarse',
      'form.plate_incomplete': 'Completa los 6 caracteres de la placa',
      'form.success_manual': 'Registro exitoso. Inicia sesión manualmente.',
      'form.register_error': 'Error al registrar usuario',
      'form.password_requirements': 'Requisitos de contraseña',
      'form.min_twelve': 'Mínimo 12 caracteres',
      'form.one_number': 'Al menos un número',
      'form.special_character': 'Al menos un carácter especial (!@#\$&*~)',

      'map.title': 'Mapa de estacionamientos',
      'map.subtitle': 'Verifica estacionamientos cerca de ti',
      'map.detecting': 'Detectando...',
      'map.gps_active': 'GPS activo',
      'map.no_gps': 'Sin GPS',
      'map.search': 'Buscar',
      'map.detecting_location': 'Detectando tu ubicación...',
      'map.unavailable': 'Ubicación no disponible',
      'map.enable_help':
          'Activa el GPS para ver los\nestacionamientos más cercanos a ti',
      'map.enable_location': 'Activar ubicación',
      'map.user_location': 'Tu ubicación',
      'map.search_legend': 'Búsqueda',
      'map.nearby_affiliates': 'Afiliados cercanos',
      'map.verified_zones': 'Zonas verificadas',
      'map.watched': 'Vigilados 24/7',
      'map.my_location': 'Mi ubicación',
      'map.refresh': 'Actualizar',
      'map.location_detected': 'Ubicación detectada correctamente.',
      'map.write_place': 'Escribe un lugar para buscar.',
      'map.location_found': 'Ubicación encontrada: {query}',
      'map.search_hint': 'Buscar dirección o lugar...',
      'nav.parking': 'Parking',
      'nav.plans': 'Planes',
      'nav.map': 'Mapa',
      'nav.my_data': 'Mis datos',
      'nav.about': 'Acerca de',

      'parking_list.title': 'Estacionamientos',
      'parking_list.affiliates': '{total} afiliados',
      'parking_list.subtitle':
          'Selecciona un estacionamiento afiliado\npara ver su información y disponibilidad',
      'parking_list.affiliate': 'Afiliado',
      'parking_list.spaces': '{count} espacios',
      'parking_list.view_details': 'Ver detalles',
      'parking_list.institution': 'Institución',
      'parking_list.description': 'Descripción',
      'parking_list.address': 'Dirección',
      'parking_list.capacity': 'Capacidad',
      'parking_list.total_spaces': '{count} espacios totales',
      'parking_list.availability': 'Disponible 24/7 · Vigilancia permanente',
      'parking_list.close': 'Cerrar',
      'parking_list.view_on_map': 'Ver en el mapa',
      'parking_list.empty': 'No hay estacionamientos afiliados.',

      'profile.title': 'Mis datos',
      'profile.unavailable': 'No disponible',
      'profile.active_user': 'Usuario activo',
      'profile.personal_info': 'Información personal',
      'profile.name': 'Nombre',
      'profile.surname': 'Apellido',
      'profile.phone': 'Teléfono',
      'profile.birth_date': 'Fecha de nacimiento',
      'profile.status': 'Estado',
      'profile.verified': 'Verificado',
      'profile.vehicle': 'Vehículo',
      'profile.registered': 'Registrado',
      'profile.edit': 'Modificar mis datos',
      'profile.logout': 'Cerrar sesión',
      'profile.in_development': 'Funcionalidad en desarrollo',

      'about.title': 'Acerca de',
      'about.who_we_are': '¿Quiénes somos?',
      'about.description':
          'Somos una empresa dedicada a optimizar la experiencia de estacionamiento en universidades, centros comerciales y corporaciones. Nuestro objetivo es brindar seguridad, comodidad y tecnología de punta para que tu vehículo siempre esté en el mejor lugar.',
      'about.affiliated_spaces': 'Espacios\nafiliados',
      'about.always_available': 'Disponible\nsiempre',
      'about.satisfied_customers': 'Clientes\nsatisfechos',
      'about.offerings': 'Lo que ofrecemos',
      'about.smart_parking': 'Estacionamientos inteligentes en tiempo real',
      'about.realtime_maps': 'Mapas en tiempo real',
      'about.realtime_maps_subtitle':
          'Visualiza disponibilidad al instante desde la app',
      'about.history': 'Historial de uso',
      'about.history_subtitle':
          'Consulta tus ingresos y egresos cuando quieras',
      'about.security': 'Seguridad garantizada',
      'about.security_subtitle': 'Acceso controlado y monitoreo constante 24/7',
      'about.technology': 'Nuestra tecnología',
      'about.one_app': 'Una sola app para gestionar todo',
      'about.tech_description':
          'Con SmartParking Solutions podrás acceder a estacionamientos afiliados, visualizar mapas en tiempo real y gestionar tu historial de uso desde una sola aplicación.',
      'about.view_parking': 'Ver estacionamientos',

      'premium.title': 'Planes de Suscripción',
      'premium.subtitle': 'Elige el plan que mejor se adapta a ti',
      'premium.basic_plan': 'Plan Básico',
      'premium.basic_subtitle': 'Para explorar sin compromiso',
      'premium.free': 'Gratis',
      'premium.no_cost': 'Sin costo',
      'premium.limited_access': 'Acceso limitado a estacionamientos',
      'premium.basic_map': 'Visualización básica del mapa',
      'premium.default_ads': 'Anuncios por defecto',
      'premium.basic_description':
          'Ideal para usuarios que solo necesitan una vista rápida de estacionamientos cercanos.',
      'premium.premium_plan': 'Plan Premium',
      'premium.complete_experience': 'La experiencia completa',
      'premium.everything_basic': 'Todo lo del Plan Básico',
      'premium.history': 'Historial de estacionamientos usados',
      'premium.ai_info': 'Información exclusiva con IA',
      'premium.no_ads': 'Sin anuncios',
      'premium.priority_support': 'Soporte prioritario 24/7',
      'premium.premium_description':
          'Diseñado para usuarios frecuentes que buscan comodidad, predicción inteligente y una experiencia sin interrupciones.',
      'premium.subscribe': 'Suscribirme ahora',
      'premium.continue_free': 'Continuar gratis',

      'parking_map.default_name': 'Estacionamiento',
      'parking_map.default_description': 'Estacionamiento 24/7',
      'parking_map.no_data': 'Sin datos',
      'parking_map.total_spaces': 'ESPACIOS TOTALES',
      'parking_map.floor_summary': 'RESUMEN POR PISO',
      'parking_map.level': 'Nivel',
      'parking_map.distribution': 'DISTRIBUCIÓN',
      'parking_map.zone': 'Zona',
    },
    'en': {
      'common.light_mode': 'Light mode',
      'common.dark_mode': 'Dark mode',

      'login.brand_description':
          'Manage parking across universities,\nshopping centers, and more',
      'login.welcome': 'Welcome',
      'login.subtitle': 'Sign in to continue',
      'login.email': 'Email',
      'login.password': 'Password',
      'login.sign_in': 'Sign in',
      'login.register': "Don't have an account? Register here",
      'login.company_prompt':
          'Are you a company? Visit our exclusive business portal.',
      'login.company_action': 'Go to business portal',
      'login.company_error': 'Could not open the business portal',
      'login.empty_credentials': 'Enter email and password',
      'login.invalid_credentials': 'Incorrect email or password',

      'register.create_account': 'Create account',
      'register.step_one': 'Step 1 of 2 — Email verification',
      'register.info':
          'Enter your email to validate your account. We will send you a 6-digit verification code.',
      'register.email': 'Email',
      'register.private_info': 'Your information is protected and private',
      'register.send_code': 'Send verification code',
      'register.enter_email': 'Please enter an email',
      'register.error': 'Could not register user. Please try again.',
      'register.already_account': 'Already have an account? Sign in',
      'register.next_steps': 'What happens next?',
      'register.receive_code': 'Receive the code',
      'register.receive_code_subtitle': 'In your inbox in under 2 minutes',
      'register.enter_digits': 'Enter the 6 digits',
      'register.enter_digits_subtitle': 'Valid for 10 minutes after sending',
      'register.complete_profile': 'Complete your profile',
      'register.complete_profile_subtitle':
          'Set up your account and start using the app',

      'validation.title': 'Verify account',
      'validation.step_two': 'Step 2 of 2 — Enter your code',
      'validation.sent_to': 'Code sent to',
      'validation.code': 'Verification code',
      'validation.code_help': 'Enter the 6 digits sent to your email',
      'validation.expiry': 'The code expires in 10 minutes',
      'validation.not_received': "Didn't receive the code? ",
      'validation.resend': 'Resend',
      'validation.validate_user': 'Validate user',
      'validation.complete_digits': 'Enter all 6 digits',
      'validation.invalid_code': 'Invalid or expired code',

      'form.final_step': 'Final step',
      'form.title': 'Complete your registration',
      'form.subtitle': 'Fill in every field to create your account',
      'form.personal_data': 'Personal data',
      'form.names': 'First names',
      'form.surnames': 'Last names',
      'form.enter_names': 'Enter your first names',
      'form.enter_surnames': 'Enter your last names',
      'form.valid_dni': 'Enter a valid ID',
      'form.phone': 'Phone',
      'form.valid_phone': 'Enter a valid phone number',
      'form.birth_date': 'Birth date',
      'form.select_date': 'Select your date',
      'form.vehicle_data': 'Vehicle data',
      'form.plate': 'License plate',
      'form.model': 'Car model',
      'form.enter_model': 'Enter the model',
      'form.credentials': 'Credentials',
      'form.password': 'Password',
      'form.repeat_password': 'Repeat password',
      'form.min_chars': 'Minimum 8 characters',
      'form.passwords_mismatch': 'Passwords do not match',
      'form.register': 'Register',
      'form.plate_incomplete': 'Complete all 6 plate characters',
      'form.success_manual': 'Registration successful. Sign in manually.',
      'form.register_error': 'Could not register user',
      'form.password_requirements': 'Password requirements',
      'form.min_twelve': 'Minimum 12 characters',
      'form.one_number': 'At least one number',
      'form.special_character': 'At least one special character (!@#\$&*~)',

      'map.title': 'Parking map',
      'map.subtitle': 'Check parking spots near you',
      'map.detecting': 'Detecting...',
      'map.gps_active': 'GPS active',
      'map.no_gps': 'No GPS',
      'map.search': 'Search',
      'map.detecting_location': 'Detecting your location...',
      'map.unavailable': 'Location unavailable',
      'map.enable_help':
          'Enable GPS to see the\nclosest parking spots near you',
      'map.enable_location': 'Enable location',
      'map.user_location': 'Your location',
      'map.search_legend': 'Search',
      'map.nearby_affiliates': 'Nearby affiliates',
      'map.verified_zones': 'Verified zones',
      'map.watched': 'Monitored 24/7',
      'map.my_location': 'My location',
      'map.refresh': 'Refresh',
      'map.location_detected': 'Location detected successfully.',
      'map.write_place': 'Type a place to search.',
      'map.location_found': 'Location found: {query}',
      'map.search_hint': 'Search address or place...',
      'nav.parking': 'Parking',
      'nav.plans': 'Plans',
      'nav.map': 'Map',
      'nav.my_data': 'My data',
      'nav.about': 'About',

      'parking_list.title': 'Parking',
      'parking_list.affiliates': '{total} affiliates',
      'parking_list.subtitle':
          'Select an affiliated parking lot\nto view its details and availability',
      'parking_list.affiliate': 'Affiliate',
      'parking_list.spaces': '{count} spaces',
      'parking_list.view_details': 'View details',
      'parking_list.institution': 'Institution',
      'parking_list.description': 'Description',
      'parking_list.address': 'Address',
      'parking_list.capacity': 'Capacity',
      'parking_list.total_spaces': '{count} total spaces',
      'parking_list.availability': 'Available 24/7 · Permanent surveillance',
      'parking_list.close': 'Close',
      'parking_list.view_on_map': 'View on map',
      'parking_list.empty': 'There are no affiliated parking lots.',

      'profile.title': 'My data',
      'profile.unavailable': 'Unavailable',
      'profile.active_user': 'Active user',
      'profile.personal_info': 'Personal information',
      'profile.name': 'Name',
      'profile.surname': 'Surname',
      'profile.phone': 'Phone',
      'profile.birth_date': 'Birth date',
      'profile.status': 'Status',
      'profile.verified': 'Verified',
      'profile.vehicle': 'Vehicle',
      'profile.registered': 'Registered',
      'profile.edit': 'Edit my data',
      'profile.logout': 'Log out',
      'profile.in_development': 'Feature in development',

      'about.title': 'About',
      'about.who_we_are': 'Who are we?',
      'about.description':
          'We are a company dedicated to improving the parking experience across universities, shopping centers, and corporations. Our goal is to provide safety, comfort, and advanced technology so your vehicle is always in the best place.',
      'about.affiliated_spaces': 'Affiliated\nspaces',
      'about.always_available': 'Always\navailable',
      'about.satisfied_customers': 'Satisfied\ncustomers',
      'about.offerings': 'What we offer',
      'about.smart_parking': 'Smart parking in real time',
      'about.realtime_maps': 'Real-time maps',
      'about.realtime_maps_subtitle': 'See availability instantly from the app',
      'about.history': 'Usage history',
      'about.history_subtitle':
          'Review your entries and exits whenever you want',
      'about.security': 'Guaranteed security',
      'about.security_subtitle':
          'Controlled access and constant 24/7 monitoring',
      'about.technology': 'Our technology',
      'about.one_app': 'One app to manage everything',
      'about.tech_description':
          'With SmartParking Solutions you can access affiliated parking lots, view real-time maps, and manage your usage history from one app.',
      'about.view_parking': 'View parking',

      'premium.title': 'Subscription Plans',
      'premium.subtitle': 'Choose the plan that best fits you',
      'premium.basic_plan': 'Basic Plan',
      'premium.basic_subtitle': 'Explore with no commitment',
      'premium.free': 'Free',
      'premium.no_cost': 'No cost',
      'premium.limited_access': 'Limited parking access',
      'premium.basic_map': 'Basic map view',
      'premium.default_ads': 'Default ads',
      'premium.basic_description':
          'Ideal for users who only need a quick view of nearby parking.',
      'premium.premium_plan': 'Premium Plan',
      'premium.complete_experience': 'The complete experience',
      'premium.everything_basic': 'Everything in the Basic Plan',
      'premium.history': 'Used parking history',
      'premium.ai_info': 'Exclusive AI information',
      'premium.no_ads': 'No ads',
      'premium.priority_support': 'Priority support 24/7',
      'premium.premium_description':
          'Designed for frequent users seeking comfort, smart prediction, and an uninterrupted experience.',
      'premium.subscribe': 'Subscribe now',
      'premium.continue_free': 'Continue free',

      'parking_map.default_name': 'Parking',
      'parking_map.default_description': 'Parking 24/7',
      'parking_map.no_data': 'No data',
      'parking_map.total_spaces': 'TOTAL SPACES',
      'parking_map.floor_summary': 'FLOOR SUMMARY',
      'parking_map.level': 'Level',
      'parking_map.distribution': 'DISTRIBUTION',
      'parking_map.zone': 'Zone',
    },
  };

  static String text(
    String key, {
    Locale? locale,
    TranslationParams params = const {},
  }) {
    final language =
        locale?.languageCode ?? AppPreferences.instance.locale.languageCode;
    final template =
        _translations[language]?[key] ?? _translations['es']?[key] ?? key;

    return params.entries.fold(
      template,
      (result, entry) =>
          result.replaceAll('{${entry.key}}', entry.value.toString()),
    );
  }
}

extension LocalizedBuildContext on BuildContext {
  String tr(String key, [TranslationParams params = const {}]) {
    return AppLocalizations.text(
      key,
      locale: AppPreferencesScope.watch(this).locale,
      params: params,
    );
  }
}
