import { Injectable, signal } from '@angular/core';

export type AppLanguage = 'es' | 'en';

type TranslationParams = Record<string, string | number>;
type TranslationMap = Record<string, string>;

const translations: Record<AppLanguage, TranslationMap> = {
  es: {
    'common.light_mode': 'Modo claro',
    'common.dark_mode': 'Modo oscuro',
    'common.spanish': 'Español',
    'common.english': 'Inglés',
    'legal.terms_title': 'Terminos y condiciones',
    'legal.privacy_title': 'Politica de privacidad',
    'legal.close': 'Cerrar',
    'legal.loading': 'Cargando documento legal...',
    'legal.load_error': 'No se pudo cargar el documento legal.',

    'login.portal_label': 'Portal empresarial',
    'login.hero_title': 'Gestión inteligente de estacionamientos',
    'login.hero_description':
      'Plataforma exclusiva para empresas. Administra, monitorea y optimiza tus espacios desde un solo lugar.',
    'login.realtime_monitoring': 'Monitoreo en tiempo real',
    'login.corporate_users': 'Gestión de usuarios corporativos',
    'login.trusted_by': 'Confiado por empresas líderes',
    'login.access_badge': 'Acceso exclusivo empresas',
    'login.welcome_back': 'Bienvenido de nuevo',
    'login.continue': 'Ingresa con tus credenciales corporativas para continuar.',
    'login.corporate_email': 'Correo corporativo',
    'login.password': 'Contraseña',
    'login.submit': 'Ingresar al portal',
    'login.loading': 'Autenticando...',
    'login.no_account': '¿No tienes cuenta?',
    'login.request_access': 'Solicita acceso empresarial',
    'login.complete_fields': 'Por favor, completa todos los campos.',
    'login.failed': 'No se pudo iniciar sesión.',
    'login.connection_error': 'Error de conexión con el servidor.',

    'register.request_badge': 'Solicitud de acceso empresarial',
    'register.title': 'Crea tu cuenta empresarial',
    'register.description': 'Completa los datos de tu empresa para solicitar acceso al portal.',
    'register.first_name': 'Nombre del representante',
    'register.last_name': 'Apellido del representante',
    'register.email': 'Correo corporativo',
    'register.company_name': 'Nombre de la Empresa / Institución',
    'register.password': 'Contraseña',
    'register.confirm_password': 'Confirmar contraseña',
    'register.accept_terms': 'Acepto los',
    'register.terms': 'términos y condiciones',
    'register.and_the': 'y la',
    'register.privacy': 'política de privacidad',
    'register.sending': 'Enviando solicitud...',
    'register.submit': 'Solicitar acceso empresarial',
    'register.already_have_account': '¿Ya tienes cuenta?',
    'register.login_here': 'Inicia sesión aquí',
    'register.hero_title': 'Únete a las empresas que confían en nosotros',
    'register.hero_description':
      'El proceso de validación es riguroso para garantizar la seguridad de la red. En menos de 24 horas recibirás una respuesta.',
    'register.complete_fields': 'Por favor, completa correctamente todos los campos.',
    'register.sent': 'Solicitud enviada correctamente.',
    'register.sent_email_warning':
      'Solicitud registrada, pero no se pudo enviar el correo de confirmación. Revisa la configuración SMTP.',
    'register.error': 'Error al enviar la solicitud. Intenta de nuevo.',

    'parking.local_company': 'Empresa Local',
    'parking.verified_partner': 'Socio Verificado',
    'parking.create_parking': 'Crear Estacionamiento',
    'parking.my_parkings': 'Mis Estacionamientos',
    'parking.collapse': 'Contraer',
    'parking.logout': 'Cerrar Sesión',
    'parking.config_module': 'Módulo de configuración',
    'parking.creation_title': 'Creación de estacionamiento',
    'parking.creation_description':
      'Configura y estructura tu espacio de estacionamiento corporativo.',
    'parking.how_it_works': '¿Cómo funciona este apartado?',
    'parking.module_description':
      'Este módulo permite registrar y configurar estacionamientos de manera completa:',
    'parking.company_data': 'Datos de la empresa',
    'parking.company_data_description': 'Nombre, descripción, dirección e imagen.',
    'parking.location': 'Ubicación',
    'parking.location_description': 'Coordenadas XY de geolocalización.',
    'parking.structure': 'Estructura',
    'parking.structure_description': 'Pisos, divisiones y espacios.',
    'parking.visualization': 'Visualización',
    'parking.visualization_description': 'Mapa dinámico de distribución.',
    'parking.company_name': 'Nombre de la empresa',
    'parking.company_placeholder': 'Ej: UTP, Plaza Norte, Mall del Sur',
    'parking.short_description': 'Descripción breve',
    'parking.short_description_placeholder': 'Describe brevemente el estacionamiento',
    'parking.image_url': 'URL de la imagen del establecimiento',
    'parking.image_placeholder': 'Ej: https://mi-imagen.jpg',
    'parking.address': 'Dirección',
    'parking.address_placeholder': 'Ej: Av. Principal 123, Lima',
    'parking.geo_location': 'Ubicación geográfica',
    'parking.coordinate_x': 'Coordenada X',
    'parking.coordinate_y': 'Coordenada Y',
    'parking.parking_structure': 'Estructura del estacionamiento',
    'parking.floor_count': 'Número de pisos',
    'parking.divisions_per_floor': 'Divisiones por piso (máx 4 columnas)',
    'parking.estimated_total': 'Total estimado:',
    'parking.divisions_per_floor_suffix': 'divisiones por piso',
    'parking.spaces_per_division': 'Espacios por división',
    'parking.define_structure': 'Definir Estructura y Modificar Espacios',
    'parking.modify_spaces': 'Modificar Espacios',
    'parking.floor': 'Piso',
    'parking.division': 'División',
    'parking.back': '← Regresar',
    'parking.next_floor': 'Siguiente Piso →',
    'parking.save_database': 'Guardar Base de Datos',
    'parking.preview_empty': 'El mapa interactivo aparecerá aquí',
    'parking.my_parking': 'Mi Estacionamiento',
    'parking.realtime_config': 'Configuración en tiempo real',
    'parking.total_spaces': 'Espacios Totales',
    'parking.floor_summary': 'Resumen por Piso',
    'parking.level': 'Nivel',
    'parking.distribution_floor': 'Distribución — Piso',
    'parking.finish_config': 'Finalizar Configuración',
    'parking.enter_one_floor': 'Ingresa al menos 1 piso.',
    'parking.company_missing':
      'Error: No se pudo identificar la empresa. Por favor, inicia sesión nuevamente.',
    'parking.created_success': "¡Éxito! Estacionamiento '{name}' creado correctamente.",
    'parking.backend_error': 'No se pudo conectar con el backend.',
    'parking.save_error': 'Error al guardar: {message}',

    'admin.title': 'Panel de Control Administrativo',
    'admin.description': 'Supervisión de solicitudes y estado de hardware SmartParking.',
    'admin.pending': 'Pendientes',
    'admin.sensor_alerts': 'Alertas Sensores',
    'admin.company_validation': 'Validación de Empresas',
    'admin.company': 'Empresa',
    'admin.representative': 'Representante',
    'admin.contact': 'Contacto',
    'admin.actions': 'Acciones',
    'admin.loading_requests': 'Cargando solicitudes...',
    'admin.no_requests': 'No hay solicitudes pendientes.',
    'admin.approve': 'Aprobar',
    'admin.reject': 'Rechazar',
    'admin.inoperative_sensors': 'Sensores No Operativos (Mantenimiento)',
    'admin.immediate_action': 'ACCIÓN INMEDIATA REQUERIDA',
    'admin.parking_site': 'Estacionamiento / Sede',
    'admin.exact_location': 'Ubicación Exacta',
    'admin.sensor_code': 'Código Sensor',
    'admin.physical_state': 'Estado Físico',
    'admin.scanning_sensors': 'Escaneando red de sensores...',
    'admin.all_operational': '✅ Todos los sensores en la red están operando correctamente.',
    'admin.not_operational': 'NO OPERATIVO',
    'admin.confirm_action': '¿Estás seguro de que deseas {action} esta empresa?',
    'admin.success': 'Operación exitosa.',
    'admin.process_error': 'Error al procesar la solicitud',
    'admin.logout': 'Cerrar sesion',
  },
  en: {
    'common.light_mode': 'Light mode',
    'common.dark_mode': 'Dark mode',
    'common.spanish': 'Spanish',
    'common.english': 'English',
    'legal.terms_title': 'Terms and conditions',
    'legal.privacy_title': 'Privacy policy',
    'legal.close': 'Close',
    'legal.loading': 'Loading legal document...',
    'legal.load_error': 'Could not load the legal document.',

    'login.portal_label': 'Enterprise portal',
    'login.hero_title': 'Smart parking management',
    'login.hero_description':
      'An exclusive platform for companies. Manage, monitor, and optimize your spaces from one place.',
    'login.realtime_monitoring': 'Real-time monitoring',
    'login.corporate_users': 'Corporate user management',
    'login.trusted_by': 'Trusted by leading companies',
    'login.access_badge': 'Exclusive company access',
    'login.welcome_back': 'Welcome back',
    'login.continue': 'Sign in with your corporate credentials to continue.',
    'login.corporate_email': 'Corporate email',
    'login.password': 'Password',
    'login.submit': 'Enter portal',
    'login.loading': 'Authenticating...',
    'login.no_account': 'No account yet?',
    'login.request_access': 'Request business access',
    'login.complete_fields': 'Please complete all fields.',
    'login.failed': 'Could not sign in.',
    'login.connection_error': 'Server connection error.',

    'register.request_badge': 'Business access request',
    'register.title': 'Create your business account',
    'register.description': 'Complete your company details to request portal access.',
    'register.first_name': 'Representative first name',
    'register.last_name': 'Representative last name',
    'register.email': 'Corporate email',
    'register.company_name': 'Company / Institution name',
    'register.password': 'Password',
    'register.confirm_password': 'Confirm password',
    'register.accept_terms': 'I accept the',
    'register.terms': 'terms and conditions',
    'register.and_the': 'and the',
    'register.privacy': 'privacy policy',
    'register.sending': 'Sending request...',
    'register.submit': 'Request business access',
    'register.already_have_account': 'Already have an account?',
    'register.login_here': 'Sign in here',
    'register.hero_title': 'Join the companies that trust us',
    'register.hero_description':
      'The validation process is rigorous to keep the network secure. You will receive a response in less than 24 hours.',
    'register.complete_fields': 'Please complete all fields correctly.',
    'register.sent': 'Request sent successfully.',
    'register.sent_email_warning':
      'Request saved, but the confirmation email could not be sent. Check the SMTP settings.',
    'register.error': 'Could not send the request. Please try again.',

    'parking.local_company': 'Local Company',
    'parking.verified_partner': 'Verified Partner',
    'parking.create_parking': 'Create Parking',
    'parking.my_parkings': 'My Parkings',
    'parking.collapse': 'Collapse',
    'parking.logout': 'Log out',
    'parking.config_module': 'Configuration module',
    'parking.creation_title': 'Parking creation',
    'parking.creation_description': 'Configure and structure your corporate parking space.',
    'parking.how_it_works': 'How does this section work?',
    'parking.module_description':
      'This module lets you register and configure parking spaces end to end:',
    'parking.company_data': 'Company data',
    'parking.company_data_description': 'Name, description, address, and image.',
    'parking.location': 'Location',
    'parking.location_description': 'XY geolocation coordinates.',
    'parking.structure': 'Structure',
    'parking.structure_description': 'Floors, divisions, and spaces.',
    'parking.visualization': 'Visualization',
    'parking.visualization_description': 'Dynamic distribution map.',
    'parking.company_name': 'Company name',
    'parking.company_placeholder': 'Ex: UTP, Plaza Norte, Mall del Sur',
    'parking.short_description': 'Short description',
    'parking.short_description_placeholder': 'Briefly describe the parking lot',
    'parking.image_url': 'Venue image URL',
    'parking.image_placeholder': 'Ex: https://my-image.jpg',
    'parking.address': 'Address',
    'parking.address_placeholder': 'Ex: 123 Main Ave, Lima',
    'parking.geo_location': 'Geographic location',
    'parking.coordinate_x': 'X coordinate',
    'parking.coordinate_y': 'Y coordinate',
    'parking.parking_structure': 'Parking structure',
    'parking.floor_count': 'Number of floors',
    'parking.divisions_per_floor': 'Divisions per floor (max 4 columns)',
    'parking.estimated_total': 'Estimated total:',
    'parking.divisions_per_floor_suffix': 'divisions per floor',
    'parking.spaces_per_division': 'Spaces per division',
    'parking.define_structure': 'Define Structure and Modify Spaces',
    'parking.modify_spaces': 'Modify Spaces',
    'parking.floor': 'Floor',
    'parking.division': 'Division',
    'parking.back': '← Back',
    'parking.next_floor': 'Next Floor →',
    'parking.save_database': 'Save Database',
    'parking.preview_empty': 'The interactive map will appear here',
    'parking.my_parking': 'My Parking',
    'parking.realtime_config': 'Real-time configuration',
    'parking.total_spaces': 'Total Spaces',
    'parking.floor_summary': 'Floor Summary',
    'parking.level': 'Level',
    'parking.distribution_floor': 'Distribution — Floor',
    'parking.finish_config': 'Finish Configuration',
    'parking.enter_one_floor': 'Enter at least 1 floor.',
    'parking.company_missing':
      'Error: The company could not be identified. Please sign in again.',
    'parking.created_success': "Success! Parking '{name}' created correctly.",
    'parking.backend_error': 'Could not connect to the backend.',
    'parking.save_error': 'Save error: {message}',

    'admin.title': 'Administrative Control Panel',
    'admin.description': 'Request supervision and SmartParking hardware status.',
    'admin.pending': 'Pending',
    'admin.sensor_alerts': 'Sensor Alerts',
    'admin.company_validation': 'Company Validation',
    'admin.company': 'Company',
    'admin.representative': 'Representative',
    'admin.contact': 'Contact',
    'admin.actions': 'Actions',
    'admin.loading_requests': 'Loading requests...',
    'admin.no_requests': 'There are no pending requests.',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.inoperative_sensors': 'Inoperative Sensors (Maintenance)',
    'admin.immediate_action': 'IMMEDIATE ACTION REQUIRED',
    'admin.parking_site': 'Parking / Site',
    'admin.exact_location': 'Exact Location',
    'admin.sensor_code': 'Sensor Code',
    'admin.physical_state': 'Physical State',
    'admin.scanning_sensors': 'Scanning sensor network...',
    'admin.all_operational': '✅ All sensors on the network are operating correctly.',
    'admin.not_operational': 'NOT OPERATIONAL',
    'admin.confirm_action': 'Are you sure you want to {action} this company?',
    'admin.success': 'Operation completed successfully.',
    'admin.process_error': 'Error processing the request',
    'admin.logout': 'Log out',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly storageKey = 'smartparking.language';
  private readonly languageSignal = signal<AppLanguage>(this.getInitialLanguage());

  readonly current = this.languageSignal.asReadonly();

  setLanguage(language: AppLanguage): void {
    this.languageSignal.set(language);
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(this.storageKey, language);
    }
  }

  toggle(): void {
    this.setLanguage(this.languageSignal() === 'es' ? 'en' : 'es');
  }

  t(key: string, params: TranslationParams = {}): string {
    const template = translations[this.languageSignal()][key] ?? translations.es[key] ?? key;

    return Object.entries(params).reduce(
      (result, [param, value]) => result.replaceAll(`{${param}}`, String(value)),
      template,
    );
  }

  private getInitialLanguage(): AppLanguage {
    if (typeof window === 'undefined') return 'es';
    const stored = window.localStorage.getItem(this.storageKey);
    return stored === 'en' ? 'en' : 'es';
  }
}
